# File: k8s/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iris-api-ksa # This is the Kubernetes Service Account (KSA)
  namespace: default
  annotations:
    # This links the KSA to your Google Service Account (GSA)
    iam.gke.io/gcp-service-account: iris-api-sa@warm-cycle-351713.iam.gserviceaccount.com